name: py-sysinfo
version: '0.1'
summary: A simple Python script which displays system info.
description: |
  A simple Python script for sending system information to STDOUT. For use in
  docks and status bars commmonly used in Window Manager-only setups.

grade: stable 
confinement: strict

apps:
  py-sysinfo:
    command: bin/sysinfo.py

parts:
  sysinfo-git:
    plugin: python
    source: https://github.com/darthlukan/sysinfo.git
    python-version: python3
    stage-packages:
      - python3-psutil
    build: |
      cp sysinfo.py $SNAPCRAFT_PART_INSTALL/bin/sysinfo.py
